= Asciidoc to Wordpress blog publisher
Container that converts an asciidoc document into a Wordpress blog (in draft mode)

== Configuration

There is a configuration file required with the following 3 configuration variables:

* URL: Wordpress XML_RPC URL (don't forget to append /xmlrpc.php)
* USERNAME: Wordpress login name
* PASSWORD: Wordpress password

The file needs to be located within the current directory and needs to be named *blogpost*

There is an example file with sample contents named *blogpost.example*. Just rename it to *blogpost* and edit appropriately.

== Usage

*Docker and Asciidoctor must be installed on your computer*

Move your adoc file to be published on WordPress under adoc-files directory. 

Create your adoc file's html version:
----
asciidoctor -a allow-uri-read adoc-files/file_to_be_published.adoc
----

Under the repository's directory, run the command below once:

----
./build
----

Then for each publish, run the script with parameter which is the name of .adoc file with .html extension:

----
./publish adoc-files/file_to_be_published.html
----

